### ISSUE TITLE
Use new font setup

### ISSUE THREAD

**Issue by hmenke** [adityam/context-slides-example#1]
The tutorial still uses the `simplefonts` module.  Today `\definefontfamily` should be used instead.  I would file a pull request but changing old commits requires rebasing which is not possible as a PR.

**Comment by jurf** [comment]
In the neweset TeX Live it doesn’t compile anymore with `simplefonts`.

**Comment by adityam** [comment]
Sorry for the really late response on this. Finally fixed!
